"atom":
  # How to convert from ASP to visualizer format
  "object": 
    #TODO: maybe reverse keys and values for consistency with actions?
    "item": #Visually depicted objects
      "node": "sprites/asprilo/node.svg"
      "highway": "sprites/asprilo/highway.svg"
      "robot": "sprites/asprilo/robot.svg"
      "shelf": "sprites/asprilo/shelf.svg"
      "pickingStation": "sprites/asprilo/pickingStation.svg"
    
    "abstract": #Objects which are not visually depicted
      "order": ~ #Maybe use empty space for further specification?
      "product": ~

  # Marks which items are drawn on top of each other (ascending order, bottom first)
  "layer":
    - "node"
    - "highway"
    - "shelf"
    - "pickingStation"
    - "robot"
  
  # Marks items that can be picked up by other items. Only used in pick_up_all,
  # overruled by explicitly picking up specific item.
  "portable":
    - "shelf"

  # Marks items that will have different colors depending on their index. Paths are always colorcoded
  # like their parent
  "colorcode":
    - "robot"

  # Maps ASP actions to visualizer actions
  "action":
    "move": "move"
    "pickup": "pick_up_all"
    "putdown": "put_down_all"
    "deliver": "satisfy"
